=== Haixing-Hu/commons/src/main/resources/default-ports.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Document   : default-ports.xsd
  Description: This document is the schema for valid default-ports
               definitions. For successful parsing of default-ports
               XML files, the XML file should be validated with this 
               schema.
  See        : com.github.haixing_hu.commons.net.DefaultPortMap.java
 -->

<xsd:schema xmlns:this="http://www.ascentdimension.com"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  targetNamespace="http://www.ascentdimension.com"
  elementFormDefault="qualified">

  <xsd:element name="default-ports">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="default-port" maxOccurs="unbounded" type="this:default-port" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="default-port">
    <xsd:sequence>
      <xsd:element name="scheme" type="xsd:string"/>
      <xsd:element name="port" type="xsd:int"/>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== Haixing-Hu/commons/src/main/resources/default-ports.xml
<?xml version="1.0" encoding="UTF-8"?>
<default-ports xmlns="http://www.ascentdimension.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.ascentdimension.com default-ports.xsd ">  
	<default-port>
		<scheme>ftp</scheme>
		<port>21</port>
	</default-port>
	<default-port>
		<scheme>gopher</scheme>
		<port>70</port>
	</default-port>	
	<default-port>
		<scheme>http</scheme>
		<port>80</port>
	</default-port>
	<default-port>
		<scheme>https</scheme>
		<port>443</port>
	</default-port>	
</default-ports>
